export const usStates = [
	{ name: "ALABAMA", abbreviation: "AL" },
	{ name: "ALASKA", abbreviation: "AK" },
	{ name: "AMERICAN SAMOA", abbreviation: "AS" },
	{ name: "ARIZONA", abbreviation: "AZ" },
	{ name: "ARKANSAS", abbreviation: "AR" },
	{ name: "CALIFORNIA", abbreviation: "CA" },
	{ name: "COLORADO", abbreviation: "CO" },
	{ name: "CONNECTICUT", abbreviation: "CT" },
	{ name: "DELAWARE", abbreviation: "DE" },
	{ name: "DISTRICT OF COLUMBIA", abbreviation: "DC" },
	{ name: "FEDERATED STATES OF MICRONESIA", abbreviation: "FM" },
	{ name: "FLORIDA", abbreviation: "FL" },
	{ name: "GEORGIA", abbreviation: "GA" },
	{ name: "GUAM", abbreviation: "GU" },
	{ name: "HAWAII", abbreviation: "HI" },
	{ name: "IDAHO", abbreviation: "ID" },
	{ name: "ILLINOIS", abbreviation: "IL" },
	{ name: "INDIANA", abbreviation: "IN" },
	{ name: "IOWA", abbreviation: "IA" },
	{ name: "KANSAS", abbreviation: "KS" },
	{ name: "KENTUCKY", abbreviation: "KY" },
	{ name: "LOUISIANA", abbreviation: "LA" },
	{ name: "MAINE", abbreviation: "ME" },
	{ name: "MARSHALL ISLANDS", abbreviation: "MH" },
	{ name: "MARYLAND", abbreviation: "MD" },
	{ name: "MASSACHUSETTS", abbreviation: "MA" },
	{ name: "MICHIGAN", abbreviation: "MI" },
	{ name: "MINNESOTA", abbreviation: "MN" },
	{ name: "MISSISSIPPI", abbreviation: "MS" },
	{ name: "MISSOURI", abbreviation: "MO" },
	{ name: "MONTANA", abbreviation: "MT" },
	{ name: "NEBRASKA", abbreviation: "NE" },
	{ name: "NEVADA", abbreviation: "NV" },
	{ name: "NEW HAMPSHIRE", abbreviation: "NH" },
	{ name: "NEW JERSEY", abbreviation: "NJ" },
	{ name: "NEW MEXICO", abbreviation: "NM" },
	{ name: "NEW YORK", abbreviation: "NY" },
	{ name: "NORTH CAROLINA", abbreviation: "NC" },
	{ name: "NORTH DAKOTA", abbreviation: "ND" },
	{ name: "NORTHERN MARIANA ISLANDS", abbreviation: "MP" },
	{ name: "OHIO", abbreviation: "OH" },
	{ name: "OKLAHOMA", abbreviation: "OK" },
	{ name: "OREGON", abbreviation: "OR" },
	{ name: "PALAU", abbreviation: "PW" },
	{ name: "PENNSYLVANIA", abbreviation: "PA" },
	{ name: "PUERTO RICO", abbreviation: "PR" },
	{ name: "RHODE ISLAND", abbreviation: "RI" },
	{ name: "SOUTH CAROLINA", abbreviation: "SC" },
	{ name: "SOUTH DAKOTA", abbreviation: "SD" },
	{ name: "TENNESSEE", abbreviation: "TN" },
	{ name: "TEXAS", abbreviation: "TX" },
	{ name: "UTAH", abbreviation: "UT" },
	{ name: "VERMONT", abbreviation: "VT" },
	{ name: "VIRGIN ISLANDS", abbreviation: "VI" },
	{ name: "VIRGINIA", abbreviation: "VA" },
	{ name: "WASHINGTON", abbreviation: "WA" },
	{ name: "WEST VIRGINIA", abbreviation: "WV" },
	{ name: "WISCONSIN", abbreviation: "WI" },
	{ name: "WYOMING", abbreviation: "WY" },
];

export const usCities = [
	{ city: "New York", stateCode: "NY" },
	{ city: "Los Angeles", stateCode: "CA" },
	{ city: "Chicago", stateCode: "IL" },
	{ city: "Houston", stateCode: "TX" },
	{ city: "Phoenix", stateCode: "AZ" },
	{ city: "Philadelphia", stateCode: "PA" },
	{ city: "San Antonio", stateCode: "TX" },
	{ city: "San Diego", stateCode: "CA" },
	{ city: "Dallas", stateCode: "TX" },
	{ city: "San Jose", stateCode: "CA" },
	{ city: "Jacksonville", stateCode: "FL" },
	{ city: "Austin", stateCode: "TX" },
	{ city: "Indianapolis", stateCode: "IN" },
	{ city: "San Francisco", stateCode: "CA" },
	{ city: "Columbus", stateCode: "OH" },
	{ city: "Charlotte", stateCode: "NC" },
	{ city: "Fort Worth", stateCode: "TX" },
	{ city: "Detroit", stateCode: "MI" },
	{ city: "Memphis", stateCode: "TN" },
	{ city: "Baltimore", stateCode: "MD" },
	{ city: "Denver", stateCode: "CO" },
	{ city: "Seattle", stateCode: "WA" },
	{ city: "Las Vegas", stateCode: "NV" },
	{ city: "Miami", stateCode: "FL" },
	{ city: "El Paso", stateCode: "TX" },
	{ city: "Boston", stateCode: "MA" },
	{ city: "Washington D.C.", stateCode: "DC" },
	{ city: "Nashville", stateCode: "TN" },
	{ city: "New Orleans", stateCode: "LA" },
	{ city: "Oklahoma City", stateCode: "OK" },
	{ city: "Milwaukee", stateCode: "WI" },
	{ city: "Tucson", stateCode: "AZ" },
	{ city: "Albuquerque", stateCode: "NM" },
	{ city: "Fresno", stateCode: "CA" },
	{ city: "Sacramento", stateCode: "CA" },
	{ city: "Kansas City", stateCode: "MO" },
	{ city: "Omaha", stateCode: "NE" },
	{ city: "Raleigh", stateCode: "NC" },
	{ city: "Minneapolis", stateCode: "MN" },
	{ city: "Colorado Springs", stateCode: "CO" },
	{ city: "Virginia Beach", stateCode: "VA" },
	{ city: "Atlanta", stateCode: "GA" },
	{ city: "Wichita", stateCode: "KS" },
	{ city: "Anaheim", stateCode: "CA" },
	{ city: "Aurora", stateCode: "CO" },
	{ city: "Tampa", stateCode: "FL" },
];
