export const usCities = [
	{ city: "New York", stateCode: "NY" },
	{ city: "Los Angeles", stateCode: "CA" },
	{ city: "Chicago", stateCode: "IL" },
	{ city: "Houston", stateCode: "TX" },
	{ city: "Phoenix", stateCode: "AZ" },
	{ city: "Philadelphia", stateCode: "PA" },
	{ city: "San Antonio", stateCode: "TX" },
	{ city: "San Diego", stateCode: "CA" },
	{ city: "Dallas", stateCode: "TX" },
	{ city: "San Jose", stateCode: "CA" },
	{ city: "Jacksonville", stateCode: "FL" },
	{ city: "Austin", stateCode: "TX" },
	{ city: "Indianapolis", stateCode: "IN" },
	{ city: "San Francisco", stateCode: "CA" },
	{ city: "Columbus", stateCode: "OH" },
	{ city: "Charlotte", stateCode: "NC" },
	{ city: "Fort Worth", stateCode: "TX" },
	{ city: "Detroit", stateCode: "MI" },
	{ city: "Memphis", stateCode: "TN" },
	{ city: "Baltimore", stateCode: "MD" },
	{ city: "Denver", stateCode: "CO" },
	{ city: "Seattle", stateCode: "WA" },
	{ city: "Las Vegas", stateCode: "NV" },
	{ city: "Miami", stateCode: "FL" },
	{ city: "El Paso", stateCode: "TX" },
	{ city: "Boston", stateCode: "MA" },
	{ city: "Washington D.C.", stateCode: "DC" },
	{ city: "Nashville", stateCode: "TN" },
	{ city: "New Orleans", stateCode: "LA" },
	{ city: "Oklahoma City", stateCode: "OK" },
	{ city: "Milwaukee", stateCode: "WI" },
	{ city: "Tucson", stateCode: "AZ" },
	{ city: "Albuquerque", stateCode: "NM" },
	{ city: "Fresno", stateCode: "CA" },
	{ city: "Sacramento", stateCode: "CA" },
	{ city: "Kansas City", stateCode: "MO" },
	{ city: "Omaha", stateCode: "NE" },
	{ city: "Raleigh", stateCode: "NC" },
	{ city: "Minneapolis", stateCode: "MN" },
	{ city: "Colorado Springs", stateCode: "CO" },
	{ city: "Virginia Beach", stateCode: "VA" },
	{ city: "Atlanta", stateCode: "GA" },
	{ city: "Wichita", stateCode: "KS" },
	{ city: "Anaheim", stateCode: "CA" },
	{ city: "Aurora", stateCode: "CO" },
	{ city: "Tampa", stateCode: "FL" },
];
