create type "public"."gift_order_type" as enum ('link', 'custom', 'store');

create table "public"."gifts_orders_links" (
    "id" bigint generated by default as identity not null,
    "gift_order_id" bigint not null,
    "link" text not null,
    "specs" text not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."gifts_orders_links" enable row level security;

alter table "public"."gifts" drop column "gift_link";

alter table "public"."gifts" drop column "gift_link_specifications";

alter table "public"."gifts" add column "type" gift_order_type not null default 'link'::gift_order_type;

CREATE UNIQUE INDEX gifts_orders_links_gift_order_id_key ON public.gifts_orders_links USING btree (gift_order_id);

CREATE UNIQUE INDEX gifts_orders_links_pkey ON public.gifts_orders_links USING btree (id);

alter table "public"."gifts_orders_links" add constraint "gifts_orders_links_pkey" PRIMARY KEY using index "gifts_orders_links_pkey";

alter table "public"."gifts" add constraint "gifts_sender_id_fkey" FOREIGN KEY (sender_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."gifts" validate constraint "gifts_sender_id_fkey";

alter table "public"."gifts_orders_links" add constraint "gifts_orders_links_gift_order_id_fkey" FOREIGN KEY (gift_order_id) REFERENCES gifts(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."gifts_orders_links" validate constraint "gifts_orders_links_gift_order_id_fkey";

alter table "public"."gifts_orders_links" add constraint "gifts_orders_links_gift_order_id_key" UNIQUE using index "gifts_orders_links_gift_order_id_key";

grant delete on table "public"."gifts_orders_links" to "anon";

grant insert on table "public"."gifts_orders_links" to "anon";

grant references on table "public"."gifts_orders_links" to "anon";

grant select on table "public"."gifts_orders_links" to "anon";

grant trigger on table "public"."gifts_orders_links" to "anon";

grant truncate on table "public"."gifts_orders_links" to "anon";

grant update on table "public"."gifts_orders_links" to "anon";

grant delete on table "public"."gifts_orders_links" to "authenticated";

grant insert on table "public"."gifts_orders_links" to "authenticated";

grant references on table "public"."gifts_orders_links" to "authenticated";

grant select on table "public"."gifts_orders_links" to "authenticated";

grant trigger on table "public"."gifts_orders_links" to "authenticated";

grant truncate on table "public"."gifts_orders_links" to "authenticated";

grant update on table "public"."gifts_orders_links" to "authenticated";

grant delete on table "public"."gifts_orders_links" to "service_role";

grant insert on table "public"."gifts_orders_links" to "service_role";

grant references on table "public"."gifts_orders_links" to "service_role";

grant select on table "public"."gifts_orders_links" to "service_role";

grant trigger on table "public"."gifts_orders_links" to "service_role";

grant truncate on table "public"."gifts_orders_links" to "service_role";

grant update on table "public"."gifts_orders_links" to "service_role";


