create table "public"."gifts_orders_custom" (
    "id" bigint generated by default as identity not null,
    "gift_id" bigint,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."gifts_orders_custom" enable row level security;

CREATE UNIQUE INDEX gifts_orders_custom_pkey ON public.gifts_orders_custom USING btree (id);

alter table "public"."gifts_orders_custom" add constraint "gifts_orders_custom_pkey" PRIMARY KEY using index "gifts_orders_custom_pkey";

alter table "public"."gifts_orders_custom" add constraint "gifts_orders_custom_gift_id_fkey" FOREIGN KEY (gift_id) REFERENCES gifts(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."gifts_orders_custom" validate constraint "gifts_orders_custom_gift_id_fkey";

grant delete on table "public"."gifts_orders_custom" to "anon";

grant insert on table "public"."gifts_orders_custom" to "anon";

grant references on table "public"."gifts_orders_custom" to "anon";

grant select on table "public"."gifts_orders_custom" to "anon";

grant trigger on table "public"."gifts_orders_custom" to "anon";

grant truncate on table "public"."gifts_orders_custom" to "anon";

grant update on table "public"."gifts_orders_custom" to "anon";

grant delete on table "public"."gifts_orders_custom" to "authenticated";

grant insert on table "public"."gifts_orders_custom" to "authenticated";

grant references on table "public"."gifts_orders_custom" to "authenticated";

grant select on table "public"."gifts_orders_custom" to "authenticated";

grant trigger on table "public"."gifts_orders_custom" to "authenticated";

grant truncate on table "public"."gifts_orders_custom" to "authenticated";

grant update on table "public"."gifts_orders_custom" to "authenticated";

grant delete on table "public"."gifts_orders_custom" to "service_role";

grant insert on table "public"."gifts_orders_custom" to "service_role";

grant references on table "public"."gifts_orders_custom" to "service_role";

grant select on table "public"."gifts_orders_custom" to "service_role";

grant trigger on table "public"."gifts_orders_custom" to "service_role";

grant truncate on table "public"."gifts_orders_custom" to "service_role";

grant update on table "public"."gifts_orders_custom" to "service_role";

create policy "ever"
on "public"."gifts_orders_custom"
as permissive
for all
to public
using (true);



