export interface Country {
	isoCode: string;
	label: string;
}

export const countries: Country[] = [
	{ isoCode: "AF", label: "Afghanistan" },
	{ isoCode: "AL", label: "Albania" },
	{ isoCode: "DZ", label: "Algeria" },
	{ isoCode: "AD", label: "Andorra" },
	{ isoCode: "AO", label: "Angola" },
	{ isoCode: "AQ", label: "Antarctica" },
	{ isoCode: "AR", label: "Argentina" },
	{ isoCode: "AM", label: "Armenia" },
	{ isoCode: "AU", label: "Australia" },
	{ isoCode: "AT", label: "Austria" },
	{ isoCode: "AZ", label: "Azerbaijan" },
	{ isoCode: "BS", label: "Bahamas" },
	{ isoCode: "BH", label: "Bahrain" },
	{ isoCode: "BD", label: "Bangladesh" },
	{ isoCode: "BB", label: "Barbados" },
	{ isoCode: "BY", label: "Belarus" },
	{ isoCode: "BE", label: "Belgium" },
	{ isoCode: "BZ", label: "Belize" },
	{ isoCode: "BJ", label: "Benin" },
	{ isoCode: "BT", label: "Bhutan" },
	{ isoCode: "BO", label: "Bolivia" },
	{ isoCode: "BA", label: "Bosnia and Herzegovina" },
	{ isoCode: "BW", label: "Botswana" },
	{ isoCode: "BR", label: "Brazil" },
	{ isoCode: "BN", label: "Brunei" },
	{ isoCode: "BG", label: "Bulgaria" },
	{ isoCode: "BF", label: "Burkina Faso" },
	{ isoCode: "BI", label: "Burundi" },
	{ isoCode: "CV", label: "Cabo Verde" },
	{ isoCode: "KH", label: "Cambodia" },
	{ isoCode: "CM", label: "Cameroon" },
	{ isoCode: "CA", label: "Canada" },
	{ isoCode: "CF", label: "Central African Republic" },
	{ isoCode: "TD", label: "Chad" },
	{ isoCode: "CL", label: "Chile" },
	{ isoCode: "CN", label: "China" },
	{ isoCode: "CO", label: "Colombia" },
	{ isoCode: "KM", label: "Comoros" },
	{ isoCode: "CG", label: "Congo (Brazzaville)" },
	{ isoCode: "CD", label: "Congo (Kinshasa)" },
	{ isoCode: "CR", label: "Costa Rica" },
	{ isoCode: "CI", label: "Côte d'Ivoire" },
	{ isoCode: "HR", label: "Croatia" },
	{ isoCode: "CU", label: "Cuba" },
	{ isoCode: "CY", label: "Cyprus" },
	{ isoCode: "CZ", label: "Czech Republic" },
	{ isoCode: "DK", label: "Denmark" },
	{ isoCode: "DJ", label: "Djibouti" },
	{ isoCode: "DM", label: "Dominica" },
	{ isoCode: "DO", label: "Dominican Republic" },
	{ isoCode: "EC", label: "Ecuador" },
	{ isoCode: "EG", label: "Egypt" },
	{ isoCode: "SV", label: "El Salvador" },
	{ isoCode: "GQ", label: "Equatorial Guinea" },
	{ isoCode: "ER", label: "Eritrea" },
	{ isoCode: "EE", label: "Estonia" },
	{ isoCode: "ET", label: "Ethiopia" },
	{ isoCode: "FJ", label: "Fiji" },
	{ isoCode: "FI", label: "Finland" },
	{ isoCode: "FR", label: "France" },
	{ isoCode: "GA", label: "Gabon" },
	{ isoCode: "GM", label: "Gambia" },
	{ isoCode: "GE", label: "Georgia" },
	{ isoCode: "DE", label: "Germany" },
	{ isoCode: "GH", label: "Ghana" },
	{ isoCode: "GR", label: "Greece" },
	{ isoCode: "GD", label: "Grenada" },
	{ isoCode: "GT", label: "Guatemala" },
	{ isoCode: "GN", label: "Guinea" },
	{ isoCode: "GW", label: "Guinea-Bissau" },
	{ isoCode: "GY", label: "Guyana" },
	{ isoCode: "HT", label: "Haiti" },
	{ isoCode: "HN", label: "Honduras" },
	{ isoCode: "HU", label: "Hungary" },
	{ isoCode: "IS", label: "Iceland" },
	{ isoCode: "IN", label: "India" },
	{ isoCode: "ID", label: "Indonesia" },
	{ isoCode: "IR", label: "Iran" },
	{ isoCode: "IQ", label: "Iraq" },
	{ isoCode: "IE", label: "Ireland" },
	{ isoCode: "IL", label: "Israel" },
	{ isoCode: "IT", label: "Italy" },
	{ isoCode: "JM", label: "Jamaica" },
	{ isoCode: "JP", label: "Japan" },
	{ isoCode: "JO", label: "Jordan" },
	{ isoCode: "KZ", label: "Kazakhstan" },
	{ isoCode: "KE", label: "Kenya" },
	{ isoCode: "KI", label: "Kiribati" },
	{ isoCode: "XK", label: "Kosovo" },
	{ isoCode: "KW", label: "Kuwait" },
	{ isoCode: "KG", label: "Kyrgyzstan" },
	{ isoCode: "LA", label: "Laos" },
	{ isoCode: "LV", label: "Latvia" },
	{ isoCode: "LB", label: "Lebanon" },
	{ isoCode: "LS", label: "Lesotho" },
	{ isoCode: "LR", label: "Liberia" },
	{ isoCode: "LY", label: "Libya" },
	{ isoCode: "LI", label: "Liechtenstein" },
	{ isoCode: "LT", label: "Lithuania" },
	{ isoCode: "LU", label: "Luxembourg" },
	{ isoCode: "MK", label: "North Macedonia" },
	{ isoCode: "MG", label: "Madagascar" },
	{ isoCode: "MW", label: "Malawi" },
	{ isoCode: "MY", label: "Malaysia" },
	{ isoCode: "MV", label: "Maldives" },
	{ isoCode: "ML", label: "Mali" },
	{ isoCode: "MT", label: "Malta" },
	{ isoCode: "MH", label: "Marshall Islands" },
	{ isoCode: "MR", label: "Mauritania" },
	{ isoCode: "MU", label: "Mauritius" },
	{ isoCode: "MX", label: "Mexico" },
	{ isoCode: "FM", label: "Micronesia" },
	{ isoCode: "MD", label: "Moldova" },
	{ isoCode: "MC", label: "Monaco" },
	{ isoCode: "MN", label: "Mongolia" },
	{ isoCode: "ME", label: "Montenegro" },
	{ isoCode: "MA", label: "Morocco" },
	{ isoCode: "MZ", label: "Mozambique" },
	{ isoCode: "MM", label: "Myanmar" },
	{ isoCode: "NA", label: "Namibia" },
	{ isoCode: "NR", label: "Nauru" },
	{ isoCode: "NP", label: "Nepal" },
	{ isoCode: "NL", label: "Netherlands" },
	{ isoCode: "NZ", label: "New Zealand" },
	{ isoCode: "NI", label: "Nicaragua" },
	{ isoCode: "NE", label: "Niger" },
	{ isoCode: "NG", label: "Nigeria" },
	{ isoCode: "KP", label: "North Korea" },
	{ isoCode: "MP", label: "Northern Mariana Islands" },
	{ isoCode: "NO", label: "Norway" },
	{ isoCode: "OM", label: "Oman" },
	{ isoCode: "PK", label: "Pakistan" },
	{ isoCode: "PW", label: "Palau" },
	{ isoCode: "PS", label: "State of Palestine" },
	{ isoCode: "PA", label: "Panama" },
	{ isoCode: "PG", label: "Papua New Guinea" },
	{ isoCode: "PY", label: "Paraguay" },
	{ isoCode: "PE", label: "Peru" },
	{ isoCode: "PH", label: "Philippines" },
	{ isoCode: "PL", label: "Poland" },
	{ isoCode: "PT", label: "Portugal" },
	{ isoCode: "PR", label: "Puerto Rico" },
	{ isoCode: "QA", label: "Qatar" },
	{ isoCode: "RS", label: "Serbia" },
	{ isoCode: "SC", label: "Seychelles" },
	{ isoCode: "SL", label: "Sierra Leone" },
	{ isoCode: "SG", label: "Singapore" },
	{ isoCode: "SK", label: "Slovakia" },
	{ isoCode: "SI", label: "Slovenia" },
	{ isoCode: "SB", label: "Solomon Islands" },
	{ isoCode: "SO", label: "Somalia" },
	{ isoCode: "ZA", label: "South Africa" },
	{ isoCode: "KR", label: "South Korea" },
	{ isoCode: "SS", label: "South Sudan" },
	{ isoCode: "ES", label: "Spain" },
	{ isoCode: "LK", label: "Sri Lanka" },
	{ isoCode: "SD", label: "Sudan" },
	{ isoCode: "SR", label: "Suriname" },
	{ isoCode: "SZ", label: "Swaziland" },
	{ isoCode: "SE", label: "Sweden" },
	{ isoCode: "CH", label: "Switzerland" },
	{ isoCode: "SY", label: "Syria" },
	{ isoCode: "TW", label: "Taiwan" },
	{ isoCode: "TJ", label: "Tajikistan" },
	{ isoCode: "TZ", label: "Tanzania" },
	{ isoCode: "TH", label: "Thailand" },
	{ isoCode: "TL", label: "Timor-Leste" },
	{ isoCode: "TG", label: "Togo" },
	{ isoCode: "TK", label: "Tokelau" },
	{ isoCode: "TO", label: "Tonga" },
	{ isoCode: "TT", label: "Trinidad and Tobago" },
	{ isoCode: "TN", label: "Tunisia" },
	{ isoCode: "TR", label: "Turkey" },
	{ isoCode: "TM", label: "Turkmenistan" },
	{ isoCode: "TV", label: "Tuvalu" },
	{ isoCode: "UG", label: "Uganda" },
	{ isoCode: "UA", label: "Ukraine" },
	{ isoCode: "AE", label: "United Arab Emirates" },
	{ isoCode: "GB", label: "United Kingdom" },
	{ isoCode: "US", label: "United States" },
	{ isoCode: "UY", label: "Uruguay" },
	{ isoCode: "UZ", label: "Uzbekistan" },
	{ isoCode: "VU", label: "Vanuatu" },
	{ isoCode: "VE", label: "Venezuela" },
	{ isoCode: "VN", label: "Vietnam" },
	{ isoCode: "WI", label: "Virgin Islands (British)" },
	{ isoCode: "VI", label: "Virgin Islands (U.S.)" },
	{ isoCode: "WF", label: "Wallis and Futuna" },
	{ isoCode: "EH", label: "Western Sahara" },
	{ isoCode: "YE", label: "Yemen" },
	{ isoCode: "ZM", label: "Zambia" },
	{ isoCode: "ZW", label: "Zimbabwe" },
];
