import type { Metadata } from "next";

import "./globals.css";

import { GeistSans } from "geist/font/sans";

import { cn } from "@theliaison/ui";

import { Providers } from "~/components/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn("min-h-dvh font-sans antialiased", GeistSans.variable)}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
